### ISSUE TITLE
CSS Animation null iterationCount results in 1 instead of infinite

### ISSUE THREAD

**Issue by ToxicBakery** [JetBrains/compose-multiplatform#2631]
The CSS Animation DSL implies that by not setting an explicit iterationCount (null) it defaults to a iteration count of infinite. Unfortunately with no iterationCount set, the animation output is an iterationCount value of 1.

- Kotlin 1.7.20
- Compose 1.2.2
- Chrome 108.0.5359.124

Example Stylesheet
```kotlin
object LoadingSpinnerStylesheet : StyleSheet(AppStylesheet) {
    private val rotationKeyframes by keyframes {
        each(0.percent) { transform { rotate(0.deg) } }
        each(100.percent) { transform { rotate(360.deg) } }
    }
    val spinner by style {
        animation(rotationKeyframes) {
            duration(5.s)
            timingFunction(AnimationTimingFunction.Linear)
        }
        property("transform-origin", "center")
        width(14.vw)
        height(14.vh)
    }
}
```

Expected Output
```css
.LoadingSpinnerStylesheet-spinner {
    animation: 5s linear 0s infinite normal none running LoadingSpinnerStylesheet-rotationKeyframes;
    transform-origin: center center;
    width: 14vw;
    height: 14vh;
}
```

Actual Output
```css
.LoadingSpinnerStylesheet-spinner {
    animation: 5s linear 0s 1 normal none running LoadingSpinnerStylesheet-rotationKeyframes;
    transform-origin: center center;
    width: 14vw;
    height: 14vh;
}
```
---
For anyone else hitting the issue, the obvious temporary workaround is to simply use an absurd iteration count which effectively circumvents the issue.
```kotlin
animation(rotationKeyframes) {
    duration(5.s)
    timingFunction(AnimationTimingFunction.Linear)
    iterationCount(Int.MAX_VALUE)
}
```
