### ISSUE TITLE
Can not display Chinese with a Tray in Windows.

### ISSUE THREAD

**Issue by michaellee123** [JetBrains/compose-multiplatform#4486]
**Describe the bug**

If it works in macOS, it's fine, but it can not work in Windows. 

<img width="141" alt="image" src="https://github.com/JetBrains/compose-multiplatform/assets/18477367/a7ab7215-5745-4ef9-842b-f565008c5812">

```kotlin
Tray(
    icon = TrayIcon,
    tooltip = "你好",
    menu = {
        Item("你好") {
            // do something
        }
    }
)
```

```kotlin
object TrayIcon : Painter() {
    override val intrinsicSize = Size(1024f, 1024f)

    override fun DrawScope.onDraw() {
        useResource("drawable/ic_icon_dark.png") {
            val image = ImageIO.read(it)
            val w = size.width.toInt()
            val h = size.height.toInt()
            val imageNew = BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB)
            imageNew.createGraphics().apply {
                drawImage(image, 0, 0, w, h, null)
                dispose()
            }
            println("width:$w, height: $h")

            drawImage(image = imageNew.toComposeImageBitmap())
        }
    }
}
```

And something else, the icon ain't clearly, I think the point is at this line:
```kotlin
//codes in [androidx.compose.ui.window.Tray.desktop.kt] line 106
    val awtIcon = remember(icon) {
        // We shouldn't use LocalDensity here because Tray's density doesn't equal it. It
        // equals to the density of the screen on which it shows. Currently Swing doesn't
        // provide us such information, it only requests an image with the desired width/height
        // (see MultiResolutionImage.getResolutionVariant). Resources like svg/xml should look okay
        // because they don't use absolute '.dp' values to draw, they use values which are
        // relative to their viewport.

        icon.toAwtImage(GlobalDensity, GlobalLayoutDirection, iconSize)// this line will make the icon blur
        icon.toAwtImage(Density(1f), LayoutDirection.Ltr) // this line will make the icon be cleaner
    }
```

**Affected platforms**
- Desktop (Windows)

**Versions**
Kotlin:       1.9.10
Groovy:       3.0.17
OS:           Windows 11 and Windows 10, maybe Windows 7 too, but I don't have it.

**Comment by eymar** [comment]
What Compose Multiplatform version are you using?
Could you please attach a complete reproducer code?

**Comment by michaellee123** [comment]
> What Compose Multiplatform version are you using? What Java version/manufacturer is used to run the app? Could you please attach a complete reproducer code (with app/window initialization)?

Compose Multiplatform version is 1.6.2, and I tried JDK version each from 17 to 21  (Amazon, Oracle , OpenJDK).

And there's another problem, if JDK version is 17 and the packageName has Chinese words, then I run `./gradlew package` it will throw an exception (so I run this app around JDK >= 18 most time). My friend told me that maybe jdk version 17 the tray menu display correctly. 

But I didn't try JDK 17 separately to see if that's right or not because I need a Chinese packageName. I don't have a Windows PC, so I'm sorry I can't try more solutions for this problem.

The app init code just same as this: [https://github.com/JetBrains/compose-multiplatform/blob/master/tutorials/Tray_Notifications_MenuBar_new/README.md](https://github.com/JetBrains/compose-multiplatform/blob/master/tutorials/Tray_Notifications_MenuBar_new/README.md )

I think that if you run a simple tray demo, and input some Chinese words into the tray's menuItem, and JDK version >= 18, you'll see this problem.

And I thought maybe Windows cannot show a UTF-8 charset word, I tried `"你好".toByteArray(Charsets.UTF_8).toString(Charset.forName("GBK"))`(and more another charsets) , it didn't work 😅.

I found that, if I use this lib: [https://github.com/dorkbox/SystemTray](https://github.com/dorkbox/SystemTray) , this lib uses `JMenu` not `Menu`, and it works, and I tried create a `JMenu` and `Menu` without tray, `JMenu` was correct, and `Menu` was wrong. But this lib has another problem, it can't display in some Windows 11 devices after mouse clicked, and has no logs. 

So in the end, I gave up on using the tray. If you're interested in solving this issue, I would be grateful.

**Comment by michaellee123** [comment]
Sorry, Compose Multiplatform version maybe 1.6.0, there's my toml file:

```toml
[versions]
compose = "1.6.2"
compose-plugin = "1.6.0"
junit = "4.13.2"
kotlin = "1.9.22"
coroutines = "1.8.0"
ktor = "2.3.8"
kamelImage = "0.9.3"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

kamel-image = { module = "media.kamel:kamel-image", version.ref = "kamelImage" }

[plugins]
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
```
