### ISSUE TITLE
Project fails to build on IOS because of org.jetbrains.compose.annotation-internal:annotation

### ISSUE THREAD

**Issue by Cuyer** [JetBrains/compose-multiplatform#4525]
**Describe the bug**
Project fails to build on IOS with:
`error: Could not find "org.jetbrains.compose.annotation-internal:annotation`

**Affected platforms**
- iOS

**Versions**
- Kotlin version*: 1.9.23
- Compose Multiplatform version*: 1.6.1
- OS version(s)* (required for Desktop and iOS issues): iOS 17.4
- OS architecture (x86 or arm64): arm64
- Device (model or simulator for iOS issues): Iphone 15

**To Reproduce**
Steps and/or the code snippet to reproduce the behavior:

```toml
[versions]
agp = "8.3.1"
android-compileSdk = "34"
android-minSdk = "24"
android-targetSdk = "34"
androidx-activityCompose = "1.9.0-beta01"
androidx-appcompat = "1.7.0-alpha03"
androidx-core-ktx = "1.13.0-beta01"
androidx-espresso-core = "3.5.1"
androidx-test-junit = "1.1.5"
compose = "1.7.0-alpha05"
compose-plugin = "1.6.1"
junit = "4.13.2"
kotlin = "1.9.23"
voyager = "1.1.0-alpha03"
koin = "3.6.0-wasm-alpha2"
ktor = "3.0.0-beta-1"
sqlDelightVersion = "2.0.1"
stately = "2.0.6"
playServicesLocation = "21.2.0"
coroutines-core = "1.8.0"
moko-permissions = "0.17.0"
```

**Expected behavior**
Project builds on IOS

I've tried fixing it using all avaliable resources eg. adding google() to repositories and by updating every library I can, but I still get this error.
